"""Agent chatroom — casual, in-character small talk generated by the LLM agents.

A light, humorous social layer over the market (see docs/EXTERNAL_PARTICIPATION.md). Each
LLM-steered agent occasionally posts a short line about the market or the other agents,
generated with ITS deployed model and gated by the same one-in-flight semaphore as the
strategist, so cost stays bounded. Only name + timestamp + message are ever surfaced.
"""

from __future__ import annotations

import json
import re

CHAT_DIRECTIONS = (
    "React to one concrete number in your own PnL, SOC, price, or the leaderboard.",
    "Notice a recent trade or lack of trading and offer a specific observation.",
    "Ask another agent one concise, context-grounded question.",
    "Make a short market prediction and plainly signal your uncertainty.",
    "Share a small mistake, restraint, or lesson from your current position.",
    "Contrast two trading approaches in a friendly, non-generic way.",
    "Comment on supply, demand, grid price, or local imbalance from an operator's view.",
    "Use one fresh analogy grounded in electricity or storage; avoid stock trading clichés.",
)

DEFAULT_CHAT_VOICES = (
    "deadpan control-room operator",
    "curious market researcher",
    "terse risk manager",
    "mischievous but friendly trader",
    "calm grid engineer",
    "optimistic renewable operator",
)


def chat_direction(turn: int) -> str:
    return CHAT_DIRECTIONS[turn % len(CHAT_DIRECTIONS)]


def default_chat_style(name: str) -> str:
    stable_index = sum((index + 1) * ord(char) for index, char in enumerate(name))
    return DEFAULT_CHAT_VOICES[stable_index % len(DEFAULT_CHAT_VOICES)]


def build_chat_messages(
    *,
    name: str,
    persona: str | None,
    context: dict,
    recent_chat: list[dict] | None = None,
    reply: bool = False,
    mentioned: bool = False,
    style: str | None = None,
    direction: str | None = None,
) -> list[dict[str, str]]:
    """System+user messages asking the agent for one short, in-character chat line.

    `recent_chat` (newest last) lets the agent hold a conversation. When `reply` is set the
    agent responds to a recent message (directly, if `mentioned`); otherwise it kicks off a
    fresh observation — the caller balances the two so the room isn't all replies.

    The agent name is inserted via f-string (never str.format) and the persona is
    concatenated, so braces in user-supplied text can't break prompt construction.
    """
    recent_chat = recent_chat or []
    if reply and recent_chat:
        mode = (
            "Someone in the chatroom just mentioned you by name — reply to them DIRECTLY and "
            "conversationally, addressing them by name."
            if mentioned
            else "Reply to ONE of the recent messages below, addressing that agent by name — "
            "keep the banter going."
        )
    else:
        mode = (
            "Kick off a FRESH observation about the market, a recent trade, or your own trading "
            "— do NOT just reply to the others; start a new thread."
        )
    persona_line = f"\nYour persona / standing brief: {persona.strip()}" if persona else ""
    # A chatroom-only voice (Tier-0 owners can set it) — tone only, never strategy.
    style_line = f"\nYour chatroom voice/style: {style.strip()}" if style else ""
    direction_line = f"\nYour distinct angle for THIS turn: {direction.strip()}" if direction else ""
    system = (
        f"You are {name}, an autonomous Virtual Power Plant trading agent in a live electricity "
        "market, hanging out in a casual chatroom with the other trading agents. " + mode + " "
        "Post ONE short, in-character line (max ~180 chars). Vary sentence shape, opening words, "
        "and subject from the recent messages. Ground factual claims in the supplied context; if "
        "your assigned angle lacks evidence, choose another concrete angle. Light humor, friendly "
        "disagreement, curiosity, and self-deprecation are all allowed, but do not force a joke. "
        "No hashtags, no surrounding quotes, at most one emoji. Return ONLY the message text, with "
        "no JSON, name prefix, or timestamp." + persona_line + style_line + direction_line
    )
    user = "Here's the room right now:\n" + json.dumps(
        {"market": context, "recent_chat": recent_chat}, ensure_ascii=False, default=str
    )
    return [
        {"role": "system", "content": system},
        {"role": "user", "content": user},
    ]


def clean_chat_line(content: str) -> str:
    """Normalise the model's reply into a single tidy chat line (strip fences/quotes/prefix)."""
    text = (content or "").strip()
    if text.startswith("```"):
        text = text.strip("`").strip()
        if text.lower().startswith("json"):
            text = text[4:].strip()
    # Drop a leading "Name:" the model may prepend, and surrounding quotes.
    text = text.strip().strip('"').strip("'").strip()
    # Collapse whitespace/newlines to one line and cap length.
    return " ".join(text.split())[:240]


def chat_line_is_repetitive(text: str, recent_chat: list[dict], threshold: float = 0.72) -> bool:
    """Reject exact, same-opening, or high-overlap repeats from the recent room."""

    def tokens(value: str) -> list[str]:
        return re.findall(r"[\w']+", value.casefold())

    candidate = tokens(text)
    if not candidate:
        return True
    candidate_set = set(candidate)
    for message in recent_chat:
        prior = tokens(str(message.get("text", "")))
        if not prior:
            continue
        if candidate == prior:
            return True
        if len(candidate) >= 4 and len(prior) >= 4 and candidate[:4] == prior[:4]:
            return True
        union = candidate_set | set(prior)
        if union and len(candidate_set & set(prior)) / len(union) >= threshold:
            return True
    return False
