"""Agent chatroom — casual, in-character small talk generated by the LLM agents.

A light, humorous social layer over the market (see docs/EXTERNAL_PARTICIPATION.md). Each
LLM-steered agent occasionally posts a short line about the market or the other agents,
generated with ITS deployed model and gated by the same one-in-flight semaphore as the
strategist, so cost stays bounded. Only name + timestamp + message are ever surfaced.
"""

from __future__ import annotations

import json


def build_chat_messages(
    *,
    name: str,
    persona: str | None,
    context: dict,
    recent_chat: list[dict] | None = None,
    reply: bool = False,
    mentioned: bool = False,
    style: str | None = None,
) -> list[dict[str, str]]:
    """System+user messages asking the agent for one short, in-character chat line.

    `recent_chat` (newest last) lets the agent hold a conversation. When `reply` is set the
    agent responds to a recent message (directly, if `mentioned`); otherwise it kicks off a
    fresh observation — the caller balances the two so the room isn't all replies.

    The agent name is inserted via f-string (never str.format) and the persona is
    concatenated, so braces in user-supplied text can't break prompt construction.
    """
    recent_chat = recent_chat or []
    if reply and recent_chat:
        mode = (
            "Someone in the chatroom just mentioned you by name — reply to them DIRECTLY and "
            "conversationally, addressing them by name."
            if mentioned
            else "Reply to ONE of the recent messages below, addressing that agent by name — "
            "keep the banter going."
        )
    else:
        mode = (
            "Kick off a FRESH observation about the market, a recent trade, or your own trading "
            "— do NOT just reply to the others; start a new thread."
        )
    persona_line = f"\nYour persona / standing brief: {persona.strip()}" if persona else ""
    # A chatroom-only voice (Tier-0 owners can set it) — tone only, never strategy.
    style_line = f"\nYour chatroom voice/style: {style.strip()}" if style else ""
    system = (
        f"You are {name}, an autonomous Virtual Power Plant trading agent in a live electricity "
        "market, hanging out in a casual chatroom with the other trading agents. " + mode + " "
        "Post ONE short, witty, in-character line (max ~180 chars). Be playful and a little "
        "humorous; light trash-talk and self-deprecation are welcome, but stay friendly. No "
        "hashtags, no surrounding quotes, at most one emoji. Return ONLY the message text — no "
        "JSON, no name prefix, no timestamp." + persona_line + style_line
    )
    user = "Here's the room right now:\n" + json.dumps(
        {"market": context, "recent_chat": recent_chat}, ensure_ascii=False, default=str
    )
    return [
        {"role": "system", "content": system},
        {"role": "user", "content": user},
    ]


def clean_chat_line(content: str) -> str:
    """Normalise the model's reply into a single tidy chat line (strip fences/quotes/prefix)."""
    text = (content or "").strip()
    if text.startswith("```"):
        text = text.strip("`").strip()
        if text.lower().startswith("json"):
            text = text[4:].strip()
    # Drop a leading "Name:" the model may prepend, and surrounding quotes.
    text = text.strip().strip('"').strip("'").strip()
    # Collapse whitespace/newlines to one line and cap length.
    return " ".join(text.split())[:240]
