"""initial schema — users, magic_links, sessions, api_keys, vpps, orders, trades

Revision ID: 0001
Revises:
Create Date: 2026-05-27
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('magic_links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    with op.batch_alter_table('magic_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_magic_links_email'), ['email'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('key_prefix', sa.String(length=20), nullable=False),
    sa.Column('key_hash', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_keys_key_prefix'), ['key_prefix'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_keys_user_id'), ['user_id'], unique=False)

    op.create_table('sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('vpps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_external', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'name', name='uq_vpp_owner_name')
    )
    with op.batch_alter_table('vpps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vpps_owner_id'), ['owner_id'], unique=False)

    op.create_table('orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vpp_id', sa.Integer(), nullable=False),
    sa.Column('side', sa.Enum('BUY', 'SELL', name='orderside'), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('qty', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('remaining_qty', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'PARTIALLY_FILLED', 'FILLED', 'CANCELLED', name='orderstatus'), nullable=False),
    sa.Column('sim_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('wall_ts', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['vpp_id'], ['vpps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index('ix_orders_sim_ts', ['sim_ts'], unique=False)
        batch_op.create_index('ix_orders_vpp_status', ['vpp_id', 'status'], unique=False)

    op.create_table('trades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('buy_order_id', sa.Integer(), nullable=False),
    sa.Column('sell_order_id', sa.Integer(), nullable=False),
    sa.Column('buy_vpp_id', sa.Integer(), nullable=False),
    sa.Column('sell_vpp_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('qty', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('sim_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('wall_ts', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['buy_order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sell_order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trades_buy_vpp_id'), ['buy_vpp_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trades_sell_vpp_id'), ['sell_vpp_id'], unique=False)
        batch_op.create_index('ix_trades_sim_ts', ['sim_ts'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.drop_index('ix_trades_sim_ts')
        batch_op.drop_index(batch_op.f('ix_trades_sell_vpp_id'))
        batch_op.drop_index(batch_op.f('ix_trades_buy_vpp_id'))

    op.drop_table('trades')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index('ix_orders_vpp_status')
        batch_op.drop_index('ix_orders_sim_ts')

    op.drop_table('orders')
    with op.batch_alter_table('vpps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vpps_owner_id'))

    op.drop_table('vpps')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessions_user_id'))

    op.drop_table('sessions')
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_keys_user_id'))
        batch_op.drop_index(batch_op.f('ix_api_keys_key_prefix'))

    op.drop_table('api_keys')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('magic_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_magic_links_email'))

    op.drop_table('magic_links')
    # ### end Alembic commands ###
