"""Idempotent, runnable platform examples for the public ecosystem catalogue."""

from __future__ import annotations

from datetime import UTC, datetime

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession, async_sessionmaker

from eflux.db.models import AgentRelease, ReleaseEvaluation, User
from eflux.db.session import get_sessionmaker
from eflux.ecosystem import service
from eflux.ecosystem.evaluation import execute_release_evaluation
from eflux.ecosystem.worker import _repository_git_commit

PLATFORM_EXAMPLE_EMAIL = "platform-examples@eflux.invalid"
PLATFORM_EXAMPLE_NAME = "Battery Shift Starter"
PLATFORM_EXAMPLE_VERSION = "1.0.0"
PLATFORM_EXAMPLE_BADGE = "Built-in Example"


def _release_definition(git_commit: str) -> dict:
    return {
        "name": PLATFORM_EXAMPLE_NAME,
        "version": PLATFORM_EXAMPLE_VERSION,
        "description": (
            "A platform-maintained battery arbitrage starter with a completed deterministic "
            "replay. Fork it to inspect or change the recipe, or deploy it directly in shadow "
            "and paper modes."
        ),
        "market": "realprice",
        "visibility": "public",
        "recipe": {
            "algorithm": "scripted",
            "agent_params": {"price_ref": "50"},
            "protocol_version": "2",
            "observation_schema_version": "4",
            "action_schema_version": "2",
            "online_learning": False,
            "fallback_strategy": "safe_hold",
            "risk_limits": {
                "max_open_orders": 20,
                "max_new_orders_per_decision": 5,
                "credit_limit_usd": 10_000,
            },
            "order_routing": {
                "markets": ["realprice"],
                "default_route": "grid",
            },
        },
        "state": {},
        "compatibility": {
            "market": "realprice",
            "profile_ids": ["battery-only"],
            "minimum_cash_usd": 0,
        },
        "environment": {
            "runtime": "eflux-managed",
            "agent_protocol_version": 2,
            "dependencies_locked": True,
            "git_commit": git_commit,
        },
        "badges": [PLATFORM_EXAMPLE_BADGE],
    }


async def seed_builtin_agent_example(
    session_factory: async_sessionmaker[AsyncSession] | None = None,
) -> tuple[int, int] | None:
    """Create and fully evaluate the public starter once.

    The example follows the same publish and evaluation paths as user releases,
    so its evidence is generated by the real replay engine rather than seeded
    presentation data.
    """

    git_commit = _repository_git_commit()
    if git_commit is None:
        return None

    factory = session_factory or get_sessionmaker()
    should_evaluate = False
    async with factory() as session:
        owner = (
            await session.execute(select(User).where(User.email == PLATFORM_EXAMPLE_EMAIL))
        ).scalar_one_or_none()
        if owner is None:
            owner = User(email=PLATFORM_EXAMPLE_EMAIL)
            session.add(owner)
            await session.flush()

        release = (
            await session.execute(
                select(AgentRelease).where(
                    AgentRelease.owner_id == owner.id,
                    AgentRelease.name == PLATFORM_EXAMPLE_NAME,
                    AgentRelease.version == PLATFORM_EXAMPLE_VERSION,
                )
            )
        ).scalar_one_or_none()
        if release is None:
            release = await service.create_agent_release(
                session,
                owner,
                _release_definition(git_commit),
            )
            await service.publish_agent_release(session, release.id, owner)
        elif PLATFORM_EXAMPLE_BADGE not in release.badges:
            release.badges = [*release.badges, PLATFORM_EXAMPLE_BADGE]

        evaluation = (
            await session.execute(
                select(ReleaseEvaluation)
                .where(
                    ReleaseEvaluation.release_id == release.id,
                    ReleaseEvaluation.kind == "deterministic_replay",
                )
                .order_by(ReleaseEvaluation.id)
                .limit(1)
            )
        ).scalar_one_or_none()
        if evaluation is None:
            evaluation = await service.create_release_evaluation(
                session,
                release.id,
                owner,
                {
                    "kind": "deterministic_replay",
                    "config": {
                        "profile_id": "battery-only",
                        "interval_count": 12,
                        "seeds": [11],
                        "grid_price_usd_per_mwh": 50,
                        "example_id": "battery-shift-starter-v1",
                    },
                },
            )

        if evaluation.status in {"queued", "failed"}:
            evaluation.status = "running"
            evaluation.started_at = datetime.now(UTC)
            evaluation.finished_at = None
            evaluation.error = None
            should_evaluate = True

        release_id = release.id
        evaluation_id = evaluation.id
        await session.commit()

    if should_evaluate:
        await execute_release_evaluation(evaluation_id, factory)
    return release_id, evaluation_id
